version: "3.4"

services:

  react:
    image: "containerregistryarianahorvath30441.azurecr.io/arianahorvath30441frontend:latest"
    domainname: "arianahorvath30441frontend"
    ports:
       - 80:80
    deploy: 
          resources:
            reservations:
              cpus: '1'
              memory: 2G